all:addition.o subtraction.o multiplication.o division.o
addition.o: addition.cpp addition.h
subtraction.o: subtraction.cpp subtraction.h
multiplication.o: multiplication.cpp multiplication.h
division.o: division.cpp division.h

clean:
	rm *.o -f

