LIBDIR = lib
CPP = g++
FLAGS = -g
RM = rm -f 
OBJS = $(LIBDIR)/addition.o $(LIBDIR)/division.o main.o $(LIBDIR)/multiplication.o $(LIBDIR)/subtraction.o
all: $(OBJS) 
	$(CPP) $(FLAGS) -o all $(OBJS) 
	
clean:
	$(RM) $(OBJS) all
